### ISSUE TITLE
Check out gnorm

### ISSUE THREAD

**Issue by natefinch** [lbryio/chainquery#1]
Hi @tiger5226, I noticed you posting on xo's issues page.  XO is good software, but is not very actively maintained right now.  You should check out https://github.com/gnormal/gnorm - I wrote it after I got frustrated with xo's lack of progress and lack of flexibility.  There's docs at https://gnorm.org . It's under active development and we use it at Mattel.

Sorry, I know this is not the most appropriate place to put this, but I wasn't sure how else to contact you.

**Comment by kauffj** [comment]
Entirely appropriate - thank you @natefinch!

I'll leave it to @tiger5226 to close this once he sees it.

**Comment by tiger5226** [comment]
Hi Nate, I actually do the same thing. It is the normal way to contact people when they don't have their email public. Personally I am not a fan of spam. 

I actually did checkout gnorm. We currently use SQLBoiler, of which I am not too happy with, but it works, with a lot of work. My intention here is to develop a datastore interface, and I would like to support multiple backends. gnorm and sqlboiler, support the same amount of databases. I tried to checkout XO due to the number of supported databases. However, as you saw from the issue I posted, that was a big fail. So I just stopped in my tracks there. 

GNORM is still at the top of my list. I wanted to get something working fast, so I went with what I knew and what others knew. There are a number of issues with SQLBoiler, but I also saw concerning things with GNORM that make it more complex ( like the comment that it is not expected to work out of the box ) than SQLBoiler. Even so, SQLBoiler, has basically not been touched much for quite some time, so I am still planning on checking out GNORM and will probably implement it here.
