### ISSUE TITLE
Abandoned claims not updated

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/chainquery#104]
Abandoned claims are not showing up as spent. This should happen as part of the mempool processing also. 

https://baremetal.chainquery.lbry.io/api/sql?query=SELECT%20*%20FROM%20claim%20where%20name=%22test-announce-03%22

**Comment by tiger5226** [comment]
I looked into this. There are only 51 claims out of 750K with this problem. All of them should be marked spent instead of what they are. 


Below is the list:

| name                                 |  claim_id                                 |  height |  bid_state   |  effective_amount |  valid_at_height | 
|--------------------------------------|-------------------------------------------|---------|--------------|-------------------|------------------| 
| @test17                              |  96e98842162f8135a048ebb78c6e68dcba2a2cfa |  0      |  Expired     |  10000000         |  524049          | 
| @JaviRiD                             |  c81cd3881df8ad0887931f69e92a6bf5af3d33d1 |  317849 |  Controlling |  1000000000       |  317849          | 
| acueducto14954285898o                |  fb457831960368ed043cf7a065f336c45e2e712b |  318352 |  Controlling |  500000000        |  318352          | 
| @xxx                                 |  ecbfe05be37770b812cfbe9e3d81c3544d758121 |  358226 |  Controlling |  1500000000       |  360868          | 
| test1                                |  a910a3c4af35f58341c1eeb0500fce3a243ea74f |  427171 |  Active      |  10000000         |  428862          | 
| @LBRYSupporters                      |  21ec3d11ee55d8a8aae691485d8af982371f4f7b |  462348 |  Controlling |  100000000000     |  462348          | 
| @Cavey65-myPlaylist                  |  aa68548ce74799a2dd6218ca826c5200877f4459 |  482000 |  Controlling |  10000000         |  482000          | 
| ten1212                              |  d1b53ed6f4903e9ced4bdcba177652e17e64192f |  489664 |  Controlling |  10000000         |  489664          | 
| code2                                |  1fb82c6367730b272e9b23b6d243569af75a7387 |  492941 |  Controlling |  10000000         |  492941          | 
| 456-ABC-cde                          |  7f37434e6d9637ee6345063fa2d1731203fec102 |  493058 |  Controlling |  112345600        |  493058          | 
| testsubs1                            |  b31c5dfb25b12cc3b10f7d3679188547438ee65d |  502816 |  Controlling |  10000000         |  502816          | 
| @Utopia                              |  0fd9bb8b0b856a100c514b5793851fffa868902b |  509060 |  Controlling |  10000000         |  509060          | 
| reftestoldsdk                        |  db8d9f425ee82f24fba7e9ff099a223346c89bc5 |  514084 |  Controlling |  10000000         |  514084          | 
| six                                  |  4fab1a9c93540b888c79074e7b2c8e3f13b76881 |  515439 |  Active      |  100000000        |  515450          | 
| -----                                |  f941fbba252eef07b2159d31c290f9799cf494fd |  520739 |  Controlling |  10000000         |  520739          | 
| @lbryc                               |  cc84c5db838f541349e4627b2a7f16c882b3d904 |  522142 |  Accepted    |  0                |  522725          | 
| GreenBook2018WEB-DLRipAVCOlLanDGroup |  8222dcacd923ce9d986d20bb50c05fd44188067c |  522705 |  Controlling |  30000000         |  522705          | 
| @asd                                 |  48c58ec6c99f28614ad502ae2e7e6944418360bf |  523210 |  Controlling |  10000000         |  523210          | 
| 10x102018BDRipAVCOlLanDGroup         |  75358a97b658efa7c8dc8fb5e1dde33194156230 |  523212 |  Controlling |  30000000         |  523212          | 
| VelvetBuzzsaw2019KlaydX              |  eafa75b33d664a0e68883ae5e7c7ee332e08834e |  523221 |  Controlling |  30000000         |  523221          | 
| test1                                |  64be6c3c5ede0e823b94042b8fbed55dec2c486c |  524049 |  Active      |  0                |  0               | 
| 123                                  |  9e6d5f69afbdd1b9f1ca5c072826794d699dde01 |  524273 |  Active      |  0                |  0               | 
| asdasda                              |  5a76eee6addeb898acdc208f0039dddb30991219 |  524447 |  Active      |  0                |  0               | 
| lbrytsttrees                         |  cd7e0dbd2e5a9eca0a1f876e0c9dc0503d45085a |  524541 |  Controlling |  1000000          |  524541          | 
| Quicksandthumbnail                   |  64fcb8dcd33fd1c7bb208caed7363bf8ff4ad1b8 |  525036 |  Controlling |  10000000         |  525036          | 
| ZvezdaRodilas2018DUAL720p-           |  8bb60cc49242a5037c62982d1952d49022cb4831 |  525430 |  Controlling |  30000000         |  525430          | 
| ZvezdaRodilas2018DUAL720p-HELLYWOOD  |  d7db62e0fb8b3d3170a37e9b8454c649b5f1b80f |  525598 |  Controlling |  30000000         |  525598          | 
| test123123123123                     |  67007c45954b503be51a741e60f086dc4dc99a16 |  525917 |  Controlling |  1000000          |  525917          | 
| MediaMovieClassicsDOALeadIn          |  1df703aeed59a3bfe5d5101413773cb2c3f7c895 |  526485 |  Controlling |  10000000         |  526485          | 
| who13                                |  8aaac9a108b9d4d98b65f8bea02d1570b618780e |  527148 |  Controlling |  1000000          |  527148          | 
| 07h57q485b201                        |  dedde1b638fcc7ab55078eecdecaaa2a3dba567c |  527483 |  Active      |  0                |  0               | 
| Me2                                  |  00acd6a9b74fdb73203f28224afce5eae8900149 |  527666 |  Active      |  10000000         |  527666          | 
| 1ChanProgrammer                      |  4d9b093e3abede4fa589665d6a093505e71720ed |  527668 |  Controlling |  10000000         |  527668          | 
| @goldenapple                         |  1690a25b6484864d97f97599cb322e783442350d |  528179 |  Controlling |  1000000000       |  528179          | 
| As                                   |  4a9d11b110a98db6b359668c499a8679de324ab9 |  528402 |  Active      |  10000000         |  528402          | 
| Sherifa-DancesingMiniconcert         |  2fa43212a0be412104094341f40d1a2c61b30620 |  528436 |  Controlling |  10000000         |  528436          | 
| Sophia-DancesingMiniconcert          |  7a6b3e8eb23a6d4d9c209f7899717dd0681f8679 |  528438 |  Controlling |  10000000         |  528438          | 
| x-lbry                               |  7e347502fd457db871bfd690400b67b09bd485cc |  528809 |  Controlling |  1000000          |  528809          | 
| ACCircuits1stEdition-Davis2017       |  4c575690fa7f1622d7db2c78d915738466719f34 |  529260 |  Controlling |  10000000         |  529260          | 
| Unknown1JanFeb2012                   |  b62e5705b6135d2e5cb97216d84999de26b94a3c |  529353 |  Controlling |  10000            |  529353          | 
| Unknown1January1954                  |  349d792952642750a3be1457874e9bea4260b49a |  529353 |  Controlling |  10000            |  529353          | 
| UnknownJanuary195                    |  42eea27e93b24832743226f0b82338fdf71e2a59 |  529357 |  Controlling |  10000            |  529357          | 
| January1957                          |  e0ee76a844764e1cb329b4b7b95efffb11552a2e |  529362 |  Controlling |  10000            |  529362          | 
| January1958                          |  ef264820ad8dcf378616b8f325614ce929922eb2 |  529362 |  Controlling |  10000            |  529362          | 
| BLOG-TITLE---Brainpod-Media          |  a043310eb4055a4923640a656ab7e37755e28267 |  529758 |  Controlling |  10000000         |  529758          | 
| x-lbry2                              |  b3e9653a093fcc4b31c5ad347d10dc7646a2085c |  530336 |  Controlling |  1000000          |  530336          | 
| thievery                             |  7a9f8a1d5adde043929bdc10b16753315ce3ef0e |  530352 |  Controlling |  100000           |  530352          | 
| myrwesadfasdf                        |  26cbbde9794d68bd03e3c39080bfcce947fcaed4 |  532451 |  Controlling |  10000            |  532451          | 
| myrwesadfasdfsdffsdf                 |  1cbcfbeb7b2df0650cd93e3e0f75ece34bcf5b43 |  532467 |  Controlling |  10000            |  532467          | 
| test-announce-03                     |  420588aef5b6bc2156fcebc5853bb86b6f81d829 |  532817 |  Controlling |  10000000         |  532817          | 
| covertest                            |  503884941bee289ef647843bfec3eba243d3f0d4 |  533007 |  Controlling |  10000000         |  533007          |

**Comment by tiger5226** [comment]
I don't have a reproduction scenario but the small volume of incorrect `bid_state`'s aligns with what I suspect to be the problem...timestamps. These are only recorded in seconds in the database. So an output could be processed within the same second as the start time of the claimtrie sync. We use a `>` and we should use `>=` if we want to catch this case. I pushed a fix for this but we will have to wait and see if it continues to happen.

**Comment by tzarebczan** [comment]
Can we please fix this once and for all?

**Comment by tzarebczan** [comment]
Related: https://github.com/lbryio/chainquery/issues/117

**Comment by tiger5226** [comment]
solved with https://github.com/lbryio/chainquery/pull/134
