### ISSUE TITLE
Support new metadata / types

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/chainquery#105]
Support new metadata added in types: https://github.com/lbryio/types/blob/a6f2fd6d5f382f0012383b9076d650c1f6791ada/v2/proto/claim.proto#L29

Also, the NSFW/Mature field is changing to a tag

**Comment by kauffj** [comment]
@tiger5226 have you concerned a design (or is chainquery already designed?) so that metadata definitions can propagate fully to SQL without any manual work?

If it is already designed this way, there will likely be work to add generic support for one-to-many properties on a claim (tags in the pending types changes).

**Comment by tiger5226** [comment]
That is an interesting idea. It is not designed yet. If new meta data is added, it requires a migration to add the additional columns. 

I had never thought of an automatic migration based on a library import. Is this what you meant? Like when we compile we auto generate a sql migration for adding missing columns/relationships dynamically?

**Comment by tiger5226** [comment]
solved with 1.8 release
