### ISSUE TITLE
Claims with blank names (URLs)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/chainquery#122]
There are over 5K claims with a blank claim names in chainquery and they all actually have names.

This messes up tipping from internal-apis and search results (the app displays none when it encounters this).

**Comment by tzarebczan** [comment]
There are over 8K now. @tiger5226 can we take a look to see why this is happening?

**Comment by nikooo777** [comment]
@tzarebczan can you please provide us an example?

**Comment by nikooo777** [comment]
```mysql> SELECT height FROM chainquery.claim where name = '';  
+--------+
| height |
+--------+
|  25469 |
|  25478 |
|  25481 |
|  25490 |
|  25518 |
|  31472 |
|  36601 |
|  38224 |
|  42010 |
|  44932 |
|  78265 |
|  94856 |
| 105003 |
| 199536 |
| 210006 |
| 517949 |
| 524820 |
| 589924 |
| 589956 |
| 591680 |
| 605965 |
| 609296 |
|      0 |
|      0 |
| 620068 |
|      0 |
|      0 |
| 653711 |
| 654477 |
| 654477 |
| 654477 |
| 654477 |
| 654477 |
| 654477 |
| 654477 |
| 654477 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
| 654478 |
+--------+
```
it looks like they're grouped together, perhaps this happens when CQ restarts?

**Comment by tiger5226** [comment]
This was the result of a claim being deleted when a block is rolled back that it was updated in. Because it was incorrectly being deleted when an updated was rolled back, when the update is reprocessed it creates a claim ( because it's missing ) with just the claim_id. This is required to prevent errors when its missing. The incorrect deletion has been resolved with https://github.com/lbryio/chainquery/pull/134 but I also added 077a4c27216e0fe8e40fc5dafcae6ffd1199a79b this which will also set the name just in case it happens in the future for a different reason.
