### ISSUE TITLE
transaction.value is always empty

### ISSUE THREAD

**Issue by kauffj** [lbryio/chainquery#34]
I'm not 100% certain what this is supposed to be storing, but presumably if it is always zero it's not doing whatever it's supposed to.

```
mysql> SELECT DISTINCT(value) FROM transaction;
+------------+
| value      |
+------------+
| 0.00000000 |
+------------+
1 row in set (16.43 sec)
```

**Comment by tiger5226** [comment]
`value` field is a remnant from using the explorer schema as a starting point. We should remove it if we will not use it. Since we are processing transactions, their inputs & outputs, we will need to find a way to ensure all inputs & outputs for a transaction are completed processing before summing all of the `transaction_addresses`'s if we want to use this value.

**Comment by tiger5226** [comment]
This is slated for removal.

**Comment by tiger5226** [comment]
will removed with https://github.com/lbryio/chainquery/issues/35 solution.
