### ISSUE TITLE
Technical Design for Claim Updates / Reorgs

### ISSUE THREAD

**Issue by tiger5226** [lbryio/chainquery#48]
<img width="649" alt="screen shot 2018-09-15 at 11 06 38 am" src="https://user-images.githubusercontent.com/3402064/45587715-8bef5f00-b8d7-11e8-8b5b-f290a27df6dd.png">

I created a diagram showing how the relevant data relates to one another. A Block has 1 to many transactions that it owns. If we delete a block the transactions get deleted. A transaction owns its outputs ( 1  to many ). It also owns its claims. If we delete the transaction the claim will also be deleted. 

Reorg Handling: When we process a block we validate that the previous hash of the block matches the highest recorded block's hash. If they don't match, this means there has been a reorganization and a new longest chain has been selected. We then "rollback" until we have matching hashes. We rollback by deleting the top block. This in turn deletes all the transactions, outputs, claims etc. associated with this block. 

Claim Handling: When we process an output for a claim name, we create a record in the claim table and associate it with the transaction as its owner. When we process an output for a claim update, we update the record in the claim table, and associate it with the transaction for the update. 

Since we make the new transaction the owner of the claim, if that transaction comes from a block thats part of a reorg, it will be deleted. This works fine if the this was for a claim name. We want the claim to be removed. However, in the event that this was for an update to a claim, we don't want to delete the claim if there is a reorg. We want to rollback the update to the claim.

Ideally the solution we come up with should maintain the simple handling of block reorganizations. Otherwise we risk adding lots of code debt if we have to support complex reorg handling for an extremely rare case. 

I think the best way to cover this case, is to have a background job that restores a claim that has hit this problem. Basically we check this with a query. All `output`s have a `claim_id` [column](https://github.com/lbryio/chainquery/blob/master/db/chainquery_schema.sql#L278) that links to a claim in the `claim` table. By default this column is null. If there is a claim associated with it we the claimid is in this column. So the query is to check if there are any outputs that exist where the `claim_id` column is not null and does not have a corresponding claim row in a left join.  Below is the query:

```SQL
SELECT output.transaction_hash,output.vout,output.claim_id FROM output
LEFT JOIN claim ON claim.claim_id = output.claim_id
WHERE output.claim_id IS NOT NULL
AND claim.id IS NULL
```

@lyoshenka - Thoughts?

**Comment by lyoshenka** [comment]
I think we should update the db schema to match the structure of our data better. Claims don't actually get updated in the blockchain as they do in a normal db. Instead they get updated the same way a file gets changed in git - by applying a set of diffs. 

There are several ways to do this. Here's one proposal:

- drop the `claim<->output` relation
- add a new table called `claim_diff` (or better name?). this has a 1-1 relation to `output` and a 1-N relation to `claim` (a claim has many diffs).
- drop the `claim<->transaction` relation. a claim can span multiple transactions and its already connected to them via outputs
- add a `latest_claim_diff_id` field to `claim`

A `claim_diff` stores the set of changes introduced by an output. The initial diff will be equivalent to creating a new claim. Subsequent diffs will change certain values in the claim (e.g. the metadata, the fee, etc).

The current values of a `claim` should always be equivalent to taking the outputs in order and applying them one by one. Let's say there's a function `generateClaim(diffs)` that takes all the known diffs for a claim and generates the current value of the claim (this will be handy later). 

The `latest_claim_diff_id` should always have the outpoint (or some other id) of the most recent diff (though this may become out of sync during a reorg).

When a reorg happens, `transaction`s get deleted. This deletes the associated `output`s and `claim_diff`s. It may also create new `claim_diff`s as new transactions get added.

After a new block (or set of blocks) is added or removed, you should be able to run the following query to find any claims that need updating:

```sql
SELECT
  -- claim id 
  c.id
  -- claim's current diff id
  c.latest_claim_diff_id as curr_diff_id, 
  -- latest diff id of all diffs for that claim
  SUBSTRING_INDEX(GROUP_CONCAT(cd.latest_claim_diff_id ORDER BY o.block_height DESC, o.nout DESC), ',', 1) as latest_diff_id 
FROM claim c 
LEFT JOIN claim_diff cd ON c.id = cd.claim_id 
LEFT JOIN output o ON cd.output_id = o.id
GROUP BY c.id 
HAVING curr_diff_id != latest_diff_id
```

This will tell you what claims are out of sync. Then you just run `generateClaim()` for each claim using the new set of diffs, and update that claim to the generated value. As a bonus, this process should be idempotent so its safe to do it anytime.

Side question: how do you track abandons? what happens if a claim is abandoned, and then the abandon gets rolled back.

**Comment by kauffj** [comment]
Interesting discussion. A few comments:

- It could make sense to store _both_ diffs and versions.
- Tracking versions doesn't necessitate a table separate from claims. One could simply store all versions directly in the `claim` table (at the cost of some redundant data, like the claim ids, but how much is actually redundant?)
- The `claim_version` table could independently track which version is the latest, eliminating a join, but only if one doesn't actually need additional data from the `claim` table to do something useful.

(These are all just ideas; I'm not pushing for any of them.)

**Comment by tiger5226** [comment]
>Claims don't actually get updated in the blockchain as they do in a normal db. Instead they get updated the same way a file gets changed in git - by applying a set of diffs.

I am not so sure this is true. The blockchain stores a byte array. The value that is passed in replaces the current byte array during an update. There are no set of diffs. We would be implementing this in chainquery. 

https://github.com/lbryio/claimtrie/blob/master/claim/node.go#L107

I like the idea of the `claim_version` table though. We had talked previously about this. I think it is a good middle table that allows us to get older ones. It would expand the claim, meaning it would have the same columns as the claim table but for each output for a claim. I think the claim table should then be owned by the output of the claim_name  transaction that created the claim. So if we delete the output the `claim` gets deleted as expected. The `claim_version` should be owned by both the `claim` and the `output` that produced it. If the claim gets deleted, all the versions get deleted. If the output that it comes from is deleted, the related `claim_version` gets deleted. A `claim_update` transaction would create a new version and update the claim table. 

The handling of abandoning a claim is just the bid state. That is the only thing that changes in that case. So when we do the claimtrie sync, instead of ignoring spent claims we should "recheck" them to make sure that should still be marked as spent. 

For synchronization, we check if a claim doesn't have a associated latest version. If not it needs to be synced up.

This solves both problems. The query for older claim information should be pretty easy, while getting the latest claim version remains the same.

**Comment by tiger5226** [comment]
<img width="795" alt="screen shot 2018-09-23 at 10 53 18 am" src="https://user-images.githubusercontent.com/3402064/45929392-ea8f8b00-bf1e-11e8-9b0e-48264d60ec01.png">


@lyoshenka / @alyssaoc  I see you changed this from in progress  to triaged. However, that is the point of this issue, to come up with the design. It is part of an epic and the design part was for the current sprint. Did I miss something from the new process? I just want to make sure I am doing things correctly.

**Comment by alyssaoc** [comment]
@lyoshenka I am moving back to in progress. Any particular reason for the change?

**Comment by lyoshenka** [comment]
My mistake.

**Comment by lyoshenka** [comment]
@tiger5226 take a look at the way https://github.com/lbryio/claimtrie handles claim storage and reorgs. maybe there are useful ideas there.

**Comment by lyoshenka** [comment]
sounds like we have a design that makes sense. @tiger5226 i think the next step is to give it a shot and see if it works.

**Comment by tiger5226** [comment]
We ran into this again over the weekend, due to another bug that made this problem stick out like a sore thumb. We fixed the other bug.

**Comment by tiger5226** [comment]
With the tag updates to youtube claims the urgency of solving this has become extremely pressing as there will now be tons of updates which will make this theoretical situation a common reality.

**Comment by tiger5226** [comment]
Ok this is now solved with https://github.com/lbryio/chainquery/pull/134. I went with a simpler approach. I have added 2 columns for the tracking the update hash, vout called `transaction_hash_update` and `vout_update` respectively. This allows us to keep ownership just for the original transaction that created the claim. It solves the main problem where if a block is rolled back it winds up delete the claim if the claim was updated in that block. We only wanted it to be removed if it was created in that block.
