### ISSUE TITLE
Optionally include mempool transactions

### ISSUE THREAD

**Issue by kauffj** [lbryio/chainquery#59]
A recent problem that came up on development of Osprey project for spee.ch.

A Wordpress server and a spee.ch server both have permission to publish to the same channel.

The Wordpress server wants to publish an asset and then serve that asset via a spee.ch URL.

Since the spee.ch server uses chainquery to get the state of the blockchain, a publish from the Wordpress server will not show up on the spee.ch server until a block is confirmed.

By including mempool transactions, state can be queried as soon as a transaction is received by the network.

(This may be a terrible idea, and should be considered thoroughly before proceeding)

**Comment by kauffj** [comment]
@tiger5226 do you know how hard this would be?

**Comment by skhameneh** [comment]
What about some form of "push" support.  Websockets comes to mind, but being MySQL there needs to be additional investigation for something like this.

The problem we are facing with Spee.ch is knowing when an update is in the mempool but not confirmed to favor updates over the existing confirmed content.  @daovist

**Comment by skhameneh** [comment]
If the mempool queries are in the `claims` table, with a different attribute, this could easily cover our use case.

**Comment by tiger5226** [comment]
>The problem we are facing with Spee.ch is knowing when an update is in the mempool but not confirmed to favor updates over the existing confirmed content.

This seems like rare edgecase. It usually gets confirmed within 2.5 minutes. What do mean by "favor"? and how?

**Comment by daovist** [comment]
Unconfirmed claims must be handled one way or another. We're looking for the optimal approach.

By favor Shawn means we're querying both databases and if the speech db has been updated more recently than chainquery then returning that claim data.

**Comment by kauffj** [comment]
It's not just an update scenario, it's also for a dual publishing.

Here's a real scenario we're facing:

- For lbrypress plugin, images/videos will be published to LBRY via wordpress plugin
- The wordpress plugin can directly publish these assets to LBRY via daemon
- Assets are not servable/embeddable from spee.ch instance for 2.5 minutes after publish

**Comment by tiger5226** [comment]
@kauffj All clear. We can definitely include mempool transactions. 
@skhameneh "What about some form of "push" support." we can certainly do this. Right now you are pulling from chainquery. I can certainly build in support for push notifications to notify recipients with a publish/subscribe feature. I love websockets. Never used them in golang yet.

**Comment by tiger5226** [comment]
I have two high level options

1 - I can keep the mempool transactions separate from the blockchain. This means storing this information in a separate table. I also don't think you need to know too much. I would think you need to only check against a claim name to see if it already exists. I can have a mempool transaction table that links to a claimpool table 1 > Many. Only basic information is required with this solution. It also keeps this data separate from the confirmed blockchain. This is good because the structure of the blockchain links 1 block to many transactions and a transaction does not truly exist outside of a block. 

2 - I can process the transactions like I do with the blockchain. So all the same data gets produced. I would add a helper column to the transaction table that flags the row as `is_mempool = true` for the mempool transactions. Secondarily, we would have a special block that owns these mempool transactions until they are confirmed. This works fine until we hit potential race conditions. I would be syncing the mempool every second or so. We could run into a situation where we are processing data for a mempool transaction, and simultaneously processing a block that happened to come in just after we queried the mempool of lbrycrd. Since this is multi-threaded, the block transaction could be saved first, then the mempool sync could save it second. I would like to avoid this if possible. 

Question: I am trying to determine the database schema changes I want, but I want to make sure it aligns with the use case. Are we planning on this being a separate mempool check? Also what information at a minimum would be needed besides determining if a claim_name was used?

Question: For the push functionality, when we get a new claim we will want to notify. I plan to use a publish subscribe pattern for this. We could do web sockets for this interface. The only concern I would have right now is the complexity of a websocket api. gorilla websockets seem straightforward to implement. The question would be, do we need to persist subscriptions through restarts? I could imagine, a chainquery restart, would cause issues with the connection. How do we prefer to handle dropped connections? Will speech auto-reconnect?

**Comment by kauffj** [comment]
@tiger5226 good thoughts and analysis

1. Re: data architecture and query usage, I definitely think it makes sense for them to share a table. I'm somewhat ambivalent on whether to add a new column and think the answer would depend on the suitability of extending an existing variable. E.g. could it make sense to use `height` and/or `valid_at_height` to capture this?

1. Re: subscriptions/pushes I think this is an interesting discussion and idea but needs to be it's own item considered and discussed separately.

1. Re: deadlock, it shouldn't be too difficult to avoid this. Trivially (there's prob a better design), just have the mempool update acquire a lock shared with a block based updated ONLY before it performs the SQL update, and skip the SQL update if the block height seen is higher than the height when you recorded when you began constructing the mempool update.

**Comment by tiger5226** [comment]
agreed in the mutex lock

**Comment by tiger5226** [comment]
This has been completed. 

The mempool transactions are processed as are normal transactions from confirmed blocks. They can be differentiated by their `block_hash_id` being `MEMPOOL`. An example query below to find the mempool transactions. 

```SQL
SELECT transaction.id,transaction.block_hash_id,transaction.hash FROM transaction WHERE transaction.block_hash_id = "MEMPOOL"
```
